
project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: avax
    development:
        host: https://127.0.0.1:8545
        
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        #reverting_tx_gas_limit: 6721975
        #persist: false
        default_contract_owner: true
        chainid: 1337
        test_rpc:
            cmd: ganache-cli
            port: 8545
            gas_limit: 6721975
            accounts: 10
            #evm_version: istanbul
            mnemonic: brownie
        #brownie networks add live private host=https://127.0.0.1:8545 chainid=1337

    fuji:
      host: "https://api.avax-test.network/ext/bc/C/rpc"

    avax:
      host: "https://api.avax.network/ext/bc/C/rpc"
      explorer: https://api.snowtrace.io/api            
      #43114
      
    eth-mainnet:
      #gas_limit: 6721975
      #gas_price: 0
      host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID


compiler:
    evm_version: null
    solc:
      version: 0.8.5
    #     optimizer:
    #         enabled: true
    #         runs: 200
    #     remappings: null
    # vyper:
    #     version: 0.2.15